### ISSUE TITLE
When I use a MI mod machine with the sound addon the game crashes

### ISSUE THREAD

**Issue by Jonichimang** [TheStaticVoid/MI-Sound-Addon#12]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2024-08-29 18:25:35
Description: Ticking block entity

java.lang.NoSuchFieldError: Class aztech.modern_industrialization.machines.gui.MachineGuiParameters does not have member field 'java.lang.String blockId'
	at TRANSFORMER/mi_sound_addon@1.1.1-1.21/dev.thestaticvoid.mi_sound_addon.sound.ModSounds.playSound(ModSounds.java:100) ~[mi_sound_addon-1.1.1-1.21.jar%23262!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/modern_industrialization@2.2.18-beta/aztech.modern_industrialization.machines.components.CrafterComponent.handler$zmk000$mi_sound_addon$tickRecipeInjection(CrafterComponent.java:794) ~[Modern-Industrialization-2.2.18-beta.jar%23263!/:?] {re:mixin,re:classloading,pl:mixin:APP:mi_sound_addon.mixins.json:TickRecipeMixin from mod mi_sound_addon,pl:mixin:A}
	at TRANSFORMER/modern_industrialization@2.2.18-beta/aztech.modern_industrialization.machines.components.CrafterComponent.tickRecipe(CrafterComponent.java:262) ~[Modern-Industrialization-2.2.18-beta.jar%23263!/:?] {re:mixin,re:classloading,pl:mixin:APP:mi_sound_addon.mixins.json:TickRecipeMixin from mod mi_sound_addon,pl:mixin:A}
	at TRANSFORMER/modern_industrialization@2.2.18-beta/aztech.modern_industrialization.machines.blockentities.AbstractCraftingMachineBlockEntity.tick(AbstractCraftingMachineBlockEntity.java:91) ~[Modern-Industrialization-2.2.18-beta.jar%23263!/:?] {re:classloading}
	at TRANSFORMER/modern_industrialization@2.2.18-beta/aztech.modern_industrialization.machines.blockentities.SteamCraftingMachineBlockEntity.tick(SteamCraftingMachineBlockEntity.java:92) ~[Modern-Industrialization-2.2.18-beta.jar%23263!/:?] {re:classloading}
	at TRANSFORMER/modern_industrialization@2.2.18-beta/aztech.modern_industrialization.blocks.TickableBlock.lambda$getTicker$0(TickableBlock.java:45) ~[Modern-Industrialization-2.2.18-beta.jar%23263!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:701) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:778) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.Level.tickBlockEntities(Level.java:559) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:428) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin from mod modernfix,pl:mixin:APP:comforts.mixins.json:MixinServerSleepStatus from mod comforts,pl:mixin:APP:glitchcore.mixins.json:MixinServerLevel from mod glitchcore,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1037) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:110) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.thread_priorities.IntegratedServerMixin from mod modernfix,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at TRANSFORMER/mi_sound_addon@1.1.1-1.21/dev.thestaticvoid.mi_sound_addon.sound.ModSounds.playSound(ModSounds.java:100) ~[mi_sound_addon-1.1.1-1.21.jar%23262!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/modern_industrialization@2.2.18-beta/aztech.modern_industrialization.machines.components.CrafterComponent.handler$zmk000$mi_sound_addon$tickRecipeInjection(CrafterComponent.java:794) ~[Modern-Industrialization-2.2.18-beta.jar%23263!/:?] {re:mixin,re:classloading,pl:mixin:APP:mi_sound_addon.mixins.json:TickRecipeMixin from mod mi_sound_addon,pl:mixin:A}
	at TRANSFORMER/modern_industrialization@2.2.18-beta/aztech.modern_industrialization.machines.components.CrafterComponent.tickRecipe(CrafterComponent.java:262) ~[Modern-Industrialization-2.2.18-beta.jar%23263!/:?] {re:mixin,re:classloading,pl:mixin:APP:mi_sound_addon.mixins.json:TickRecipeMixin from mod mi_sound_addon,pl:mixin:A}
	at TRANSFORMER/modern_industrialization@2.2.18-beta/aztech.modern_industrialization.machines.blockentities.AbstractCraftingMachineBlockEntity.tick(AbstractCraftingMachineBlockEntity.java:91) ~[Modern-Industrialization-2.2.18-beta.jar%23263!/:?] {re:classloading}
	at TRANSFORMER/modern_industrialization@2.2.18-beta/aztech.modern_industrialization.machines.blockentities.SteamCraftingMachineBlockEntity.tick(SteamCraftingMachineBlockEntity.java:92) ~[Modern-Industrialization-2.2.18-beta.jar%23263!/:?] {re:classloading}
	at TRANSFORMER/modern_industrialization@2.2.18-beta/aztech.modern_industrialization.blocks.TickableBlock.lambda$getTicker$0(TickableBlock.java:45) ~[Modern-Industrialization-2.2.18-beta.jar%23263!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:701) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:778) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.Level.tickBlockEntities(Level.java:559) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
-- Block entity being ticked --
Details:
	Name: modern_industrialization:bronze_compressor // aztech.modern_industrialization.machines.blockentities.SteamCraftingMachineBlockEntity
	Block: Block{modern_industrialization:bronze_compressor}
	Block location: World: (122,75,-159), Section: (at 10,11,1 in 7,4,-10; chunk contains blocks 112,-64,-160 to 127,319,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Block: Block{modern_industrialization:bronze_compressor}
	Block location: World: (122,75,-159), Section: (at 10,11,1 in 7,4,-10; chunk contains blocks 112,-64,-160 to 127,319,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
Stacktrace:
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:701) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:778) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.Level.tickBlockEntities(Level.java:559) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:428) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin from mod modernfix,pl:mixin:APP:comforts.mixins.json:MixinServerSleepStatus from mod comforts,pl:mixin:APP:glitchcore.mixins.json:MixinServerLevel from mod glitchcore,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1037) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:110) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.thread_priorities.IntegratedServerMixin from mod modernfix,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['Jonichimang'/58, l='ServerLevel[MK-Industrial]', x=121.36, y=75.00, z=-155.97]]
	Chunk stats: 1260
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,86,0), Section: (at 0,6,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 299751 game time, 553859 day time
	Level name: MK-Industrial
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Commands: true
	Level weather: Rain time: 19323 (now: false), thunder time: 44498 (now: false)
	Known server brands: neoforge
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Loaded entity count: 62
Stacktrace:
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerLevel.fillReportDetails(ServerLevel.java:1718) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin from mod modernfix,pl:mixin:APP:comforts.mixins.json:MixinServerSleepStatus from mod comforts,pl:mixin:APP:glitchcore.mixins.json:MixinServerLevel from mod glitchcore,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1040) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:110) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.thread_priorities.IntegratedServerMixin from mod modernfix,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21-20240613.152323-srg.jar%23229!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin}

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 713917384 bytes (680 MiB) / 1342177280 bytes (1280 MiB) up to 4143972352 bytes (3952 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
	Identifier: Intel64 Family 6 Model 126 Stepping 5
	Microarchitecture: Ice Lake (Client)
	Frequency (GHz): 1.19
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MiB): 1024.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 27.20.100.8853
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MiB): 15048.69
	Virtual memory used (MiB): 7559.01
	Swap memory total (MiB): 7168.00
	Swap memory used (MiB): 225.58
	Space in storage for jna.tmpdir (MiB): available: 754439.94, total: 952593.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 754439.94, total: 952593.00
	Space in storage for io.netty.native.workdir (MiB): available: 754439.94, total: 952593.00
	Space in storage for java.io.tmpdir (MiB): available: 754439.94, total: 952593.00
	Space in storage for workdir (MiB): available: 754439.94, total: 952593.00
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx3940m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Jonichimang'/58, l='ServerLevel[MK-Industrial]', x=121.36, y=75.00, z=-155.97]]
	Active Data Packs: vanilla, mod_data, mod/sodium, mod/moremekanismprocessing (incompatible), mod/fabric_renderer_api_v1, mod/sodium_extra, mod/treeharvester, mod/commonnetworking (incompatible), mod/mekanism, mod/sophisticatedcore (incompatible), mod/clumps (incompatible), mod/journeymap (incompatible), mod/controlling (incompatible), mod/neoforge, mod/modernfix (incompatible), mod/jei (incompatible), mod/comforts (incompatible), mod/naturescompass (incompatible), mod/fabric_block_view_api_v2, mod/glitchcore (incompatible), mod/sophisticatedbackpacks (incompatible), mod/explorerscompass (incompatible), mod/mekanismgenerators, mod/fpsreducer, mod/grandpower, mod/cloth_config (incompatible), mod/corpse (incompatible), mod/trade_cycling (incompatible), mod/libipn (incompatible), mod/terrablender (incompatible), mod/fabric_api_base, mod/mousetweaks (incompatible), mod/toolbelt (incompatible), mod/biomesoplenty (incompatible), mod/jade (incompatible), mod/ae2 (incompatible), mod/modern_industrialization, mod/mi_sound_addon, mod/creativecore (incompatible), mod/spectrelib (incompatible), mod/kotlinforforge (incompatible), mod/villagersfollowemeraldblocks (incompatible), mod/curios (incompatible), mod/patchouli (incompatible), mod/collective, mod/searchables (incompatible), mod/justenoughprofessions (incompatible), mod/jei_mekanism_multiblocks (incompatible), mod/entityculling (incompatible), mod/inventoryhud (incompatible), mod/buildinggadgets2 (incompatible), mod/immediatelyfast (incompatible), mod/mekanismtools, mod/inventoryprofilesnext (incompatible), mod/appleskin (incompatible), mod/ferritecore (incompatible), mod/puzzleslib (incompatible), mod/fabric_rendering_data_attachment_v1, mod/infinitetrading, mod/journeymap_api (incompatible), mod/tradingpost (incompatible)
	Available Data Packs: bundle, trade_rebalance, vanilla, mod/ae2 (incompatible), mod/appleskin (incompatible), mod/biomesoplenty (incompatible), mod/buildinggadgets2 (incompatible), mod/cloth_config (incompatible), mod/clumps (incompatible), mod/collective, mod/comforts (incompatible), mod/commonnetworking (incompatible), mod/controlling (incompatible), mod/corpse (incompatible), mod/creativecore (incompatible), mod/curios (incompatible), mod/entityculling (incompatible), mod/explorerscompass (incompatible), mod/fabric_api_base, mod/fabric_block_view_api_v2, mod/fabric_renderer_api_v1, mod/fabric_rendering_data_attachment_v1, mod/ferritecore (incompatible), mod/fpsreducer, mod/glitchcore (incompatible), mod/grandpower, mod/immediatelyfast (incompatible), mod/infinitetrading, mod/inventoryhud (incompatible), mod/inventoryprofilesnext (incompatible), mod/jade (incompatible), mod/jei (incompatible), mod/jei_mekanism_multiblocks (incompatible), mod/journeymap (incompatible), mod/journeymap_api (incompatible), mod/justenoughprofessions (incompatible), mod/kotlinforforge (incompatible), mod/libipn (incompatible), mod/mekanism, mod/mekanismgenerators, mod/mekanismtools, mod/mi_sound_addon, mod/modern_industrialization, mod/modernfix (incompatible), mod/moremekanismprocessing (incompatible), mod/mousetweaks (incompatible), mod/naturescompass (incompatible), mod/neoforge, mod/patchouli (incompatible), mod/puzzleslib (incompatible), mod/searchables (incompatible), mod/sodium, mod/sodium_extra, mod/sophisticatedbackpacks (incompatible), mod/sophisticatedcore (incompatible), mod/spectrelib (incompatible), mod/terrablender (incompatible), mod/toolbelt (incompatible), mod/trade_cycling (incompatible), mod/tradingpost (incompatible), mod/treeharvester, mod/villagersfollowemeraldblocks (incompatible), mod_data
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 7444763445044548111
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'neoforge'; Server brand changed to 'neoforge'
	Launched Version: neoforge-21.0.167
	ModLauncher: 11.0.4+main.d2e20e43
	ModLauncher launch target: forgeclient
	ModLauncher services: 
		sponge-mixin-0.14.0+mixin.0.8.6.jar mixin PLUGINSERVICE 
		loader-4.0.23.jar slf4jfixer PLUGINSERVICE 
		loader-4.0.23.jar runtime_enum_extender PLUGINSERVICE 
		at-modlauncher-10.0.1.jar accesstransformer PLUGINSERVICE 
		loader-4.0.23.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-11.0.4.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-11.0.4.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		kotlinforforge@5.5.0
		javafml@4.0
		lowcodefml@4.0
		minecraft@4.0
	Mod List: 
		MoreMekanismProcessing-1.21-5.1.jar               |More Mekanism Processing      |moremekanismprocessing        |5.1                 |Manifest: NOSIGNATURE
		fabric-renderer-api-v1-3.4.0+acb05a39d1.jar       |Forgified Fabric Renderer API |fabric_renderer_api_v1        |3.4.0+acb05a39d1    |Manifest: NOSIGNATURE
		sodium-extra-neoforge-0.6.0-beta.1+mc1.21.1.jar   |Sodium Extra                  |sodium_extra                  |0.6.0-beta.1+mc1.21.|Manifest: NOSIGNATURE
		treeharvester-1.21.1-9.1.jar                      |Tree Harvester                |treeharvester                 |9.1                 |Manifest: NOSIGNATURE
		common-networking-neoforge-1.0.16-1.21.jar        |Common Networking             |commonnetworking              |1.0.16-1.21         |Manifest: NOSIGNATURE
		Mekanism-1.21-10.6.7.54.jar                       |Mekanism                      |mekanism                      |10.6.7              |Manifest: NOSIGNATURE
		sophisticatedcore-1.21-0.6.31.631.jar             |Sophisticated Core            |sophisticatedcore             |0.6.31              |Manifest: NOSIGNATURE
		Clumps-neoforge-1.21-18.0.0.2.jar                 |Clumps                        |clumps                        |18.0.0.2            |Manifest: NOSIGNATURE
		journeymap-neoforge-1.21-6.0.0-beta.22.jar        |Journeymap                    |journeymap                    |1.21-6.0.0-beta.22  |Manifest: NOSIGNATURE
		Controlling-neoforge-1.21-18.0.4.jar              |Controlling                   |controlling                   |18.0.4              |Manifest: NOSIGNATURE
		neoforge-21.0.167-universal.jar                   |NeoForge                      |neoforge                      |21.0.167            |Manifest: NOSIGNATURE
		modernfix-neoforge-5.19.1+mc1.21.jar              |ModernFix                     |modernfix                     |5.19.1+mc1.21       |Manifest: NOSIGNATURE
		jei-1.21.1-neoforge-19.14.1.144.jar               |Just Enough Items             |jei                           |19.14.1.144         |Manifest: NOSIGNATURE
		comforts-neoforge-9.0.1+1.21.jar                  |Comforts                      |comforts                      |9.0.1+1.21          |Manifest: NOSIGNATURE
		NaturesCompass-1.21-3.0.3-neoforge.jar            |Nature's Compass              |naturescompass                |1.21-3.0.2-neoforge |Manifest: NOSIGNATURE
		fabric-block-view-api-v2-1.0.10+9afaaf8cd1.jar    |Forgified Fabric BlockView API|fabric_block_view_api_v2      |1.0.10+9afaaf8cd1   |Manifest: NOSIGNATURE
		GlitchCore-neoforge-1.21-2.0.0.3.jar              |GlitchCore                    |glitchcore                    |2.0.0.3             |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.21-3.20.9.1060.jar       |Sophisticated Backpacks       |sophisticatedbackpacks        |3.20.9              |Manifest: NOSIGNATURE
		ExplorersCompass-1.21-3.0.2-neoforge.jar          |Explorer's Compass            |explorerscompass              |1.21-3.0.2-neoforge |Manifest: NOSIGNATURE
		MekanismGenerators-1.21-10.6.7.54.jar             |Mekanism: Generators          |mekanismgenerators            |10.6.7              |Manifest: NOSIGNATURE
		sodium-neoforge-0.6.0-beta.1+mc1.21.jar           |Sodium                        |sodium                        |0.6.0-beta.1+mc1.21 |Manifest: NOSIGNATURE
		FpsReducer2-neoforge-1.21-2.10.jar                |FPS Reducer                   |fpsreducer                    |1.21-2.10           |Manifest: NOSIGNATURE
		GrandPower-3.0.0.jar                              |Grand Power                   |grandpower                    |3.0.0               |Manifest: NOSIGNATURE
		cloth-config-15.0.130-neoforge.jar                |Cloth Config v15 API          |cloth_config                  |15.0.130            |Manifest: NOSIGNATURE
		corpse-neoforge-1.21.1-1.0.14.jar                 |Corpse                        |corpse                        |1.21.1-1.0.14       |Manifest: NOSIGNATURE
		client-1.21-20240613.152323-srg.jar               |Minecraft                     |minecraft                     |1.21                |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		trade-cycling-neoforge-1.21.1-1.0.14.jar          |Trade Cycling                 |trade_cycling                 |1.21.1-1.0.14       |Manifest: NOSIGNATURE
		libIPN-neoforge-1.21-6.0.2.jar                    |libIPN                        |libipn                        |6.0.2               |Manifest: NOSIGNATURE
		TerraBlender-neoforge-1.21-4.0.0.2.jar            |TerraBlender                  |terrablender                  |4.0.0.2             |Manifest: NOSIGNATURE
		fabric-api-base-0.4.42+d1308dedd1.jar             |Forgified Fabric API Base     |fabric_api_base               |0.4.42+d1308dedd1   |Manifest: NOSIGNATURE
		MouseTweaks-neoforge-mc1.21-2.26.1.jar            |Mouse Tweaks                  |mousetweaks                   |2.26.1              |Manifest: NOSIGNATURE
		ToolBelt-1.21-2.2.3.jar                           |Tool Belt                     |toolbelt                      |2.2.3               |Manifest: NOSIGNATURE
		BiomesOPlenty-neoforge-1.21-21.0.0.15.jar         |Biomes O' Plenty              |biomesoplenty                 |21.0.0.15           |Manifest: NOSIGNATURE
		Jade-1.21-NeoForge-15.1.6.jar                     |Jade                          |jade                          |15.1.6+neoforge     |Manifest: NOSIGNATURE
		appliedenergistics2-19.0.19-beta.jar              |Applied Energistics 2         |ae2                           |19.0.19-beta        |Manifest: NOSIGNATURE
		Modern-Industrialization-2.2.18-beta.jar          |Modern Industrialization      |modern_industrialization      |2.2.18-beta         |Manifest: NOSIGNATURE
		mi_sound_addon-1.1.1-1.21.jar                     |MI Sound Addon                |mi_sound_addon                |1.1.1-1.21          |Manifest: NOSIGNATURE
		CreativeCore_NEOFORGE_v2.12.6_mc1.21.jar          |CreativeCore                  |creativecore                  |2.12.6              |Manifest: NOSIGNATURE
		spectrelib-neoforge-0.17.2+1.21.jar               |SpectreLib                    |spectrelib                    |0.17.2+1.21         |Manifest: NOSIGNATURE
		kffmod-5.5.0.jar                                  |Kotlin For Forge              |kotlinforforge                |5.5.0               |Manifest: NOSIGNATURE
		villagersfollowemeraldblocks-1.1.0.jar            |Villagers Follow Emerald Block|villagersfollowemeraldblocks  |1.1.0               |Manifest: NOSIGNATURE
		curios-neoforge-9.1.2+1.21.0.jar                  |Adorned API                   |curios                        |9.1.2+1.21.0        |Manifest: NOSIGNATURE
		Patchouli-1.21-87-NEOFORGE-SNAPSHOT.jar           |Patchouli                     |patchouli                     |1.21-87-NEOFORGE-SNA|Manifest: NOSIGNATURE
		collective-1.21.1-7.84.jar                        |Collective                    |collective                    |7.84                |Manifest: NOSIGNATURE
		Searchables-neoforge-1.21-1.0.5.jar               |Searchables                   |searchables                   |1.0.5               |Manifest: NOSIGNATURE
		JustEnoughProfessions-neoforge-1.21-4.0.1.jar     |Just Enough Professions (JEP) |justenoughprofessions         |4.0.1               |Manifest: NOSIGNATURE
		JustEnoughMekanismMultiblocks-1.21-6.5.jar        |Just Enough Mekanism Multibloc|jei_mekanism_multiblocks      |6.5                 |Manifest: NOSIGNATURE
		entityculling-neoforge-1.7.0-mc1.21.jar           |EntityCulling                 |entityculling                 |1.7.0               |Manifest: NOSIGNATURE
		inventoryhud.neoforged.1.21-3.4.26.jar            |Inventory HUD+                |inventoryhud                  |3.4.26              |Manifest: NOSIGNATURE
		buildinggadgets2-1.3.7.jar                        |Building Gadgets 2            |buildinggadgets2              |1.3.7               |Manifest: NOSIGNATURE
		ImmediatelyFast-NeoForge-1.2.21+1.21.1.jar        |ImmediatelyFast               |immediatelyfast               |1.2.21+1.21.1       |Manifest: NOSIGNATURE
		MekanismTools-1.21-10.6.7.54.jar                  |Mekanism: Tools               |mekanismtools                 |10.6.7              |Manifest: NOSIGNATURE
		InventoryProfilesNext-neoforge-1.21-2.0.4.jar     |Inventory Profiles Next       |inventoryprofilesnext         |2.0.4               |Manifest: NOSIGNATURE
		appleskin-neoforge-mc1.21-3.0.5.jar               |AppleSkin                     |appleskin                     |3.0.5+mc1.21        |Manifest: NOSIGNATURE
		ferritecore-7.0.0-neoforge.jar                    |Ferrite Core                  |ferritecore                   |7.0.0               |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		PuzzlesLib-v21.0.24-1.21-NeoForge.jar             |Puzzles Lib                   |puzzleslib                    |21.0.24             |Manifest: NOSIGNATURE
		fabric_rendering_data_attachment_v1-0.3.46+1.21.ja|Fabric Data Attachment API    |fabric_rendering_data_attachme|0.3.46+1.21         |Manifest: NOSIGNATURE
		infinitetrading-1.21.1-4.5.jar                    |Infinite Trading              |infinitetrading               |4.5                 |Manifest: NOSIGNATURE
		journeymap-api-neoforge-2.0.0-1.21-SNAPSHOT.jar   |JourneyMap API                |journeymap_api                |2.0.0               |Manifest: NOSIGNATURE
		TradingPost-v21.0.2-1.21-NeoForge.jar             |Trading Post                  |tradingpost                   |21.0.2              |Manifest: NOSIGNATURE
	Crash Report UUID: 2f47f5aa-f3fb-400f-b8d7-66ef7d3f7c4e
	FML: 4.0.23
	NeoForge: 21.0.167

**Comment by TheStaticVoid** [comment]
Looks like tech changed the blockId field in MachineGuiParameters to be a ResourceLocation instead of a String. I'll have to update the mod to accommodate for the latest MI update.

**Comment by TheStaticVoid** [comment]
Leave this open so I can remember to fix it :P
